### ISSUE TITLE
下载转移失效，手动转移时必须填写TMDB ID才能正常转移

### ISSUE THREAD

**Issue by unhoo28** [linyuan0213/nas-tools#10]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2 8f8a46f
>
> 环境: docker
>

## 你遇到什么问题了？

> 下载转移失效，手动转移时必须填写TMDB ID才能正常转移

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 下载完成后自动转移成功

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by linyuan0213** [comment]
检查下是不是没法识别，没发识别添加自定义识别词

**Comment by unhoo28** [comment]
> 查下是不是没法识别，没发识别添加自定义识别

是没法识别，只能手动查找TMDB ID才能识别到，有时间抓一份日志看下
