### ISSUE TITLE
一直提示端口占用

### ISSUE THREAD

**Issue by k2y1982** [linyuan0213/nas-tools#18]
## 你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: 3.2.3
环境: macOS sonoma 14.4
一直提示端口占用，换回上个版本就没有问题了，在config.yaml里换了端口也没有用。关闭NASTOOL后，查看了端口占用，并没有被占用。
![微信截图_20240402154012](https://github.com/linyuan0213/nas-tools/assets/5109711/2ba3c8e5-fa3d-4852-9b1b-44877c7bed02)

**Comment by linyuan0213** [comment]
netstat -tulnp | grep 3000 查下进程是不是还在

**Comment by k2y1982** [comment]
运行前和运行后查看都没有进程占用3000端口

**Comment by linyuan0213** [comment]
> 运行前和运行后查看都没有进程占用3000端口

应该是打包出问题了，docker 就没这种问题，我先看下
