### ISSUE TITLE
添加下载器

### ISSUE THREAD

**Issue by yuzhi-jiang** [linyuan0213/nas-tools#2]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2
>
> 环境: docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
大大可以添加下载器吗，主要是aria2和pikpak

**Comment by linyuan0213** [comment]
aria2可能会考虑一下，目前是完善qb的下载

**Comment by linyuan0213** [comment]
已支持Aria2下载器，下个版本上线
