### ISSUE TITLE
新站点适配

### ISSUE THREAD

**Issue by linyuan0213** [linyuan0213/nas-tools#20]
新站点适配需求发这里

**Comment by huang3370** [comment]
> 新站点适配需求发这里
https://public.ecustpt.eu.org
这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？

**Comment by huang3370** [comment]
> > 新站点适配需求发这里
> > https://public.ecustpt.eu.org
> > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？

账号密码发你邮箱了，谢谢帮看看

**Comment by huang3370** [comment]
> > 新站点适配需求发这里
> > https://public.ecustpt.eu.org
> > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？

用代理和不用代理，都不通

**Comment by linyuan0213** [comment]
> > > 新站点适配需求发这里
> > > https://public.ecustpt.eu.org
> > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> 
> 用代理和不用代理，都不通

晚点我看下

**Comment by huang3370** [comment]
> > > > 新站点适配需求发这里
> > > > https://public.ecustpt.eu.org
> > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > 
> > 
> > 用代理和不用代理，都不通
> 
> 晚点我看下

谢谢，已发你邮箱，

**Comment by huang3370** [comment]
> > > > > 新站点适配需求发这里
> > > > > https://public.ecustpt.eu.org
> > > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > > 
> > > 
> > > 用代理和不用代理，都不通
> > 
> > 
> > 晚点我看下
> 
> 谢谢，已发你邮箱，
在次发了，你搜到吗

**Comment by linyuan0213** [comment]
收到了发自我的 iPhone在 2024年4月6日，19:54，huang3370 ***@***.***> 写道：﻿





新站点适配需求发这里
https://public.ecustpt.eu.org
这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？


用代理和不用代理，都不通

晚点我看下

谢谢，已发你邮箱，
在次发了，你搜到吗

**Comment by huang3370** [comment]
> > > > 新站点适配需求发这里
> > > > https://public.ecustpt.eu.org
> > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > 
> > 
> > 用代理和不用代理，都不通
> 
> 晚点我看下

怎么样，能搞定么

**Comment by linyuan0213** [comment]
> > > > > 新站点适配需求发这里
> > > > > https://public.ecustpt.eu.org
> > > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > > 
> > > 
> > > 用代理和不用代理，都不通
> > 
> > 
> > 晚点我看下
> 
> 怎么样，能搞定么

可以搞定，晚点上线

**Comment by linyuan0213** [comment]
> > > > > > 新站点适配需求发这里
> > > > > > https://public.ecustpt.eu.org
> > > > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > > > 
> > > > 
> > > > 用代理和不用代理，都不通
> > > 
> > > 
> > > 晚点我看下
> > 
> > 
> > 怎么样，能搞定么
> 
> 可以搞定，晚点上线

已经上线

**Comment by huang3370** [comment]
强





------------------ 原始邮件 ------------------
发件人: Lin Yuan ***@***.***&gt;
发送时间: 2024年4月7日 10:39
收件人: linyuan0213/nas-tools ***@***.***&gt;
抄送: huang3370 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [linyuan0213/nas-tools] 新站点适配 (Issue #20)





       
新站点适配需求发这里
 https://public.ecustpt.eu.org
 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
   
用代理和不用代理，都不通
  
晚点我看下
  
怎么样，能搞定么
  
可以搞定，晚点上线
  
已经上线

**Comment by huang3370** [comment]
> > > > > > > 新站点适配需求发这里
> > > > > > > https://public.ecustpt.eu.org
> > > > > > > 这个站点帮我看看测试不通，顺便解析下，这站点账号密码哟发你邮箱？
> > > > > 
> > > > > 
> > > > > 用代理和不用代理，都不通
> > > > 
> > > > 
> > > > 晚点我看下
> > > 
> > > 
> > > 怎么样，能搞定么
> > 
> > 
> > 可以搞定，晚点上线
> 
> 已经上线

不行啊，改了密码cook需要重新获取？

**Comment by linyuan0213** [comment]
改密码之后cookie肯定要重新获取

**Comment by huang3370** [comment]
q'

> 改密码之后cookie肯定要重新获取

qing不通，站点联通显示网站无法打开，和cook有关系么，我在外面无法获取新的cook

**Comment by linyuan0213** [comment]
> q'
> 
> > 改密码之后cookie肯定要重新获取
> 
> qing不通，站点联通显示网站无法打开，和cook有关系么，我在外面无法获取新的cook

ping不通和你的网络环境有关，和cookie没关

**Comment by huang3370** [comment]
> > > q'
> > > > 改密码之后cookie肯定要重新获取
> > > 
> > > 
> > > qing不通，站点联通显示网站无法打开，和cook有关系么，我在外面无法获取新的cook
> > 
> > 
> > ping不通和你的网络环境有关，和cookie没关
> 
> nas-tools测的话就是cookie有问题
太奇怪了，就是qing不通
![IMG_0622](https://github.com/linyuan0213/nas-tools/assets/165783634/9a7f0774-0e01-4618-9a28-7d4f00042fdb)

**Comment by linyuan0213** [comment]
> > > > q'
> > > > > 改密码之后cookie肯定要重新获取
> > > > 
> > > > 
> > > > qing不通，站点联通显示网站无法打开，和cook有关系么，我在外面无法获取新的cook
> > > 
> > > 
> > > ping不通和你的网络环境有关，和cookie没关
> > 
> > 
> > nas-tools测的话就是cookie有问题
> > 太奇怪了，就是qing不通
> > ![IMG_0622](https://private-user-images.githubusercontent.com/165783634/320256257-9a7f0774-0e01-4618-9a28-7d4f00042fdb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzI1MzcsIm5iZiI6MTcxMjQ3MjIzNywicGF0aCI6Ii8xNjU3ODM2MzQvMzIwMjU2MjU3LTlhN2YwNzc0LTBlMDEtNDYxOC05YTI4LTdkNGYwMDA0MmZkYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDY0MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWFhMWE4YjEzMGEwN2Y0OWJlZDEwOTVhYjkzZTg0MTk0Yzk3OTBlMDNiY2ViYTQ4NzM3NjNlODI0ODQwN2ZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k9EteTScOWJ2dOLGTF2GJC3glgepeFGZRz2MlP0K2Cc)

看下日志，你本机能打开吗

**Comment by linyuan0213** [comment]
cookie换了吗

**Comment by huang3370** [comment]
电脑手机都没问题，nastoos就不行





------------------ 原始邮件 ------------------
发件人: Lin Yuan ***@***.***&gt;
发送时间: 2024年4月7日 14:45
收件人: linyuan0213/nas-tools ***@***.***&gt;
抄送: huang3370 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [linyuan0213/nas-tools] 新站点适配 (Issue #20)





     
q'
  
改密码之后cookie肯定要重新获取
  
qing不通，站点联通显示网站无法打开，和cook有关系么，我在外面无法获取新的cook
  
ping不通和你的网络环境有关，和cookie没关
  
nas-tools测的话就是cookie有问题
 太奇怪了，就是qing不通
 
   
看下日志，你本机能打开吗

**Comment by huang3370** [comment]
换了





------------------ 原始邮件 ------------------
发件人: Lin Yuan ***@***.***&gt;
发送时间: 2024年4月7日 14:45
收件人: linyuan0213/nas-tools ***@***.***&gt;
抄送: huang3370 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [linyuan0213/nas-tools] 新站点适配 (Issue #20)





 
cookie换了吗

**Comment by linyuan0213** [comment]
> 换了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Lin Yuan ***@***.***&gt; 发送时间: 2024年4月7日 14:45 收件人: linyuan0213/nas-tools ***@***.***&gt; 抄送: huang3370 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [linyuan0213/nas-tools] 新站点适配 (Issue #20) cookie换了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

看下配置

**Comment by huang3370** [comment]
> > 换了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Lin Yuan _**@**_._**> 发送时间: 2024年4月7日 14:45 收件人: linyuan0213/nas-tools _**@**_.**_> 抄送: huang3370 _**@**_._**>, Comment _**@**_.**_> 主题: Re: [linyuan0213/nas-tools] 新站点适配 (Issue #20) cookie换了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 看下配置

![IMG_0625](https://github.com/linyuan0213/nas-tools/assets/165783634/385095bb-2b6c-4738-a699-366559b1c0b1)
![IMG_0623](https://github.com/linyuan0213/nas-tools/assets/165783634/838a2bc5-d646-4bb3-bd69-d2c52d5f242d)

**Comment by linyuan0213** [comment]
有日志吗

**Comment by huang3370** [comment]
> 有日志吗
重新。删除左右的NSAtools数据重新安装了下NASTOOLS。就可以了。
