### ISSUE TITLE
憨憨测试联通正常,但是数据统计跟资源界面都没显示..搜索也不行

### ISSUE THREAD

**Issue by ati121** [linyuan0213/nas-tools#22]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:[v3.2.3 0821cad]
> 环境: docker

![1](https://github.com/linyuan0213/nas-tools/assets/72114654/374bfc40-16b0-4a8e-a2ce-ae28cc9f1862)
![2](https://github.com/linyuan0213/nas-tools/assets/72114654/1dab769c-dfee-4ee0-ac4c-699ec3cfc79e)
![3](https://github.com/linyuan0213/nas-tools/assets/72114654/90ada11e-76f5-4400-a9a1-1b15e760534f)

**Comment by linyuan0213** [comment]
我没有这个站，所以还没有支持，麻烦提供一下种子页面和分类信息，我这边维护一下，明天应该就能上线

**Comment by ati121** [comment]
![QQ截图20240405123826](https://github.com/linyuan0213/nas-tools/assets/72114654/08548c0f-632d-486f-96dd-e34738497e59)
是这样的界面吗

**Comment by linyuan0213** [comment]
> ![QQ截图20240405123826](https://private-user-images.githubusercontent.com/72114654/319859710-08548c0f-632d-486f-96dd-e34738497e59.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTM2MTksIm5iZiI6MTcxMjI5MzMxOSwicGF0aCI6Ii83MjExNDY1NC8zMTk4NTk3MTAtMDg1NDhjMGYtNjMyZC00ODZmLTk2ZGQtZTM0NzM4NDk3ZTU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA1MDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOTRmMmM2ZmI5ZDkyY2I3YTA0YjU1OTlkNGY3NzgyZGM0NWEwYTZhNjZjNjgzMmJhYjc2MTM4M2M4OTEwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R-uEOH13s-CfVGtRfdOUzCvYCN0ym1c0hx94g3Ae62k) 是这样的界面吗

对，需要 html 文件

**Comment by linyuan0213** [comment]
> 已发大佬邮箱

👌，明天上了你测试下，有问题我好改

**Comment by ati121** [comment]
> > 已发大佬邮箱
> 
> 👌，明天上了你测试下，有问题我好改

好的.麻烦大佬

**Comment by linyuan0213** [comment]
> > > 已发大佬邮箱
> > 
> > 
> > 👌，明天上了你测试下，有问题我好改
> 
> 好的.麻烦大佬

这个站有签到吗，再给个种子详情页的

**Comment by ati121** [comment]
有签到..已发!

**Comment by linyuan0213** [comment]
> 有签到..已发!

👌

**Comment by linyuan0213** [comment]
> > 有签到..已发!
> 
> 👌

已经上了，有时间测一测有没有什么问题

**Comment by ati121** [comment]
> > > 有签到..已发!
> > 
> > 
> > 👌
> 
> 已经上了，有时间测一测有没有什么问题

谢谢大佬..测试站点资源里面打开,搜索,订阅都正常..只有数据统计里面还是不显示各种信息..

**Comment by linyuan0213** [comment]
统计这个我看下，估计还要个用户页面，憨憨这个页面改动有点大在 2024年4月6日，12:30，ati121 ***@***.***> 写道：﻿



有签到..已发!

👌

已经上了，有时间测一测有没有什么问题

谢谢大佬..测试站点资源里面打开,搜索,订阅都正常..只有数据统计里面还是不显示各种信息..

**Comment by linyuan0213** [comment]
> 统计这个我看下，估计还要个用户页面，憨憨这个页面改动有点大在 2024年4月6日，12:30，ati121 ***@***.***> 写道：﻿ 有签到..已发! 👌 已经上了，有时间测一测有没有什么问题 谢谢大佬..测试站点资源里面打开,搜索,订阅都正常..只有数据统计里面还是不显示各种信息.. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

数据统计已经修复，可以显示了

**Comment by ati121** [comment]
> > 统计这个我看下，估计还要个用户页面，憨憨这个页面改动有点大在 2024年4月6日，12:30，ati121 _**@**_._**> 写道：﻿ 有签到..已发! 👌 已经上了，有时间测一测有没有什么问题 谢谢大佬..测试站点资源里面打开,搜索,订阅都正常..只有数据统计里面还是不显示各种信息.. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> 数据统计已经修复，可以显示了

其他都正常了.还有2个不显示
![QQ截图20240407150130](https://github.com/linyuan0213/nas-tools/assets/72114654/8faa69bd-b20d-4277-a220-d884604694b4)

**Comment by linyuan0213** [comment]
> > > 统计这个我看下，估计还要个用户页面，憨憨这个页面改动有点大在 2024年4月6日，12:30，ati121 _**@**_._**> 写道：﻿ 有签到..已发! 👌 已经上了，有时间测一测有没有什么问题 谢谢大佬..测试站点资源里面打开,搜索,订阅都正常..只有数据统计里面还是不显示各种信息.. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> > 
> > 
> > 数据统计已经修复，可以显示了
> 
> 其他都正常了.还有2个不显示 ![QQ截图20240407150130](https://private-user-images.githubusercontent.com/72114654/320258980-8faa69bd-b20d-4277-a220-d884604694b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzQ4NjYsIm5iZiI6MTcxMjQ3NDU2NiwicGF0aCI6Ii83MjExNDY1NC8zMjAyNTg5ODAtOGZhYTY5YmQtYjIwZC00Mjc3LWEyMjAtZDg4NDYwNDY5NGI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2M2JmNDE3Mjc1MmE0M2NkODE4MWM5OWE1MTgwNGNkODU3ZDMyMjAwYzNhNTAxYTA0OWQ5NmE4MTdhNjk5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lhEBF_qXfmK0yWfs5hNgF4VhQzpZfmZb5sUETYlP2ko)

我改下，有个bug忘改了

**Comment by linyuan0213** [comment]
再看下应该都修复了

**Comment by ati121** [comment]
> 再看下应该都修复了

嗯.正常了.谢谢大佬
