### ISSUE TITLE
增加一个自定义识别词，从github项目自动导入的插件

### ISSUE THREAD

**Issue by jackloves111** [linyuan0213/nas-tools#24]
# 你想要新增或者改进什么功能？

### 我发现，有些电影和电视剧重名，尤其是电视剧和动漫，就需要使用自定义识别词

- 因此我建议增加一个自定义识别词，从github项目自动导入的插件，别人将自己的识别词导出，写入到gihub项目里，该款插件可以自动导入到nastool内，然后大家一起维护这个项目，可以让nastool的识别准确度不断地提高

- 比如这个蜘蛛夫人，不修改识别词是不能识别的
![2369aacc-6a08-4fc2-b52e-010c4333b5fb](https://github.com/linyuan0213/nas-tools/assets/89971817/7928e684-a7c5-4542-a11d-6b6aee0f8625)
- 增加以下识别词，可以正常识别
![13487db2-cda4-4bde-ba80-eaccfb02ef02](https://github.com/linyuan0213/nas-tools/assets/89971817/6b385ce5-0ff0-4fa6-89f3-acfd87a9e8f5)

### 如果这个可以通过插件实现，并且人人共建，那么nastool的可用性能将大大提高

![d6d61bfe-ba17-4d3e-b6c1-898fdf6cd29d](https://github.com/linyuan0213/nas-tools/assets/89971817/33261240-399f-45c8-91fa-b81266c001ea)
![e8daa6a1-c639-4d19-ab61-89567938f587](https://github.com/linyuan0213/nas-tools/assets/89971817/430786a0-c7a3-4ca8-8be1-184eae7742ba)

**Comment by linyuan0213** [comment]
这个可以做

**Comment by jackloves111** [comment]
![d06a79f6-dbd9-42a6-acfb-1a1e0f0b886b](https://github.com/linyuan0213/nas-tools/assets/89971817/34655cf2-eba4-4de3-9bdc-e1e4d6625c5b)
插件的界面我都想好了！

**Comment by huang3370** [comment]
这个很好，放个教程，让大家一起维护，很多识别不了

**Comment by huang3370** [comment]
> ![d06a79f6-dbd9-42a6-acfb-1a1e0f0b886b](https://private-user-images.githubusercontent.com/89971817/320277036-34655cf2-eba4-4de3-9bdc-e1e4d6625c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDAwNjYsIm5iZiI6MTcxMjQ5OTc2NiwicGF0aCI6Ii84OTk3MTgxNy8zMjAyNzcwMzYtMzQ2NTVjZjItZWJhNC00ZGUzLTliZGMtZTFlNGQ2NjI1YzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE0MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTFiZjVjMWVhZjIyMDZjYjAzMDQ1NGQ0MDliZTY0N2U3ODA1YjNkN2UzZGRmYzkyMzFmMTkwMzdmZjg0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AtWPATkqzryvcI_SUhcvHwkQTDmVp0cbe3frDT6Ohc4) 插件的界面我都想好了！

我最近在追哈哈哈哈哈，搞了几天，才加入识别词，hahahahaha替换为哈哈哈哈哈。就可以搜到很多资源

**Comment by linyuan0213** [comment]
> > ![d06a79f6-dbd9-42a6-acfb-1a1e0f0b886b](https://private-user-images.githubusercontent.com/89971817/320277036-34655cf2-eba4-4de3-9bdc-e1e4d6625c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDAwNjYsIm5iZiI6MTcxMjQ5OTc2NiwicGF0aCI6Ii84OTk3MTgxNy8zMjAyNzcwMzYtMzQ2NTVjZjItZWJhNC00ZGUzLTliZGMtZTFlNGQ2NjI1YzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE0MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTFiZjVjMWVhZjIyMDZjYjAzMDQ1NGQ0MDliZTY0N2U3ODA1YjNkN2UzZGRmYzkyMzFmMTkwMzdmZjg0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AtWPATkqzryvcI_SUhcvHwkQTDmVp0cbe3frDT6Ohc4) 插件的界面我都想好了！
> 
> 我最近在追哈哈哈哈哈，搞了几天，才加入识别词，hahahahaha替换为哈哈哈哈哈。就可以搜到很多资源

是的，所以下一步打算做一下这个，分为通用，电视剧，电影维护

**Comment by linyuan0213** [comment]
上了一个规则导入的插件

**Comment by huang3370** [comment]
> 上了一个规则导入的插件 需要维护一下这个仓库 [linyuan0213/MediaRecognitionRule](https://github.com/linyuan0213/MediaRecognitionRule)

规则不会上传啊。怎么弄

**Comment by linyuan0213** [comment]
> > 上了一个规则导入的插件 需要维护一下这个仓库 [linyuan0213/MediaRecognitionRule](https://github.com/linyuan0213/MediaRecognitionRule)
> 
> 规则不会上传啊。怎么弄

直接fork到你的项目然后改一下，直接合并到我这边就行

**Comment by huang3370** [comment]
> > > 上了一个规则导入的插件 需要维护一下这个仓库 [linyuan0213/MediaRecognitionRule](https://github.com/linyuan0213/MediaRecognitionRule)
> > 
> > 
> > 规则不会上传啊。怎么弄
> 
> 直接fork到你的项目然后改一下，直接合并到我这边就行

![image](https://github.com/linyuan0213/nas-tools/assets/165783634/4cfae817-fd24-4672-8475-05a9d7c5c6f2)
这样对不对点提交更改就行了？

**Comment by huang3370** [comment]
点哪里同步到你哪里去

**Comment by linyuan0213** [comment]
> 点哪里同步到你哪里去

pull request 就是拉取请求那里

**Comment by huang3370** [comment]
我拉取了一个对不对你看看

**Comment by linyuan0213** [comment]
> 我拉取了一个对不对你看看

看了，你再改一下那个 season

**Comment by huang3370** [comment]
> > 点哪里同步到你哪里去
> 
> pull request 就是拉取请求那里

![IMG_0100](https://github.com/linyuan0213/nas-tools/assets/165783634/faea3364-d3d2-4c6a-a4c5-6eb61a722ad4)
这插件日志，正确么

**Comment by linyuan0213** [comment]
> > > 点哪里同步到你哪里去
> > 
> > 
> > pull request 就是拉取请求那里
> 
> ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk) 这插件日志，正确么

对的

**Comment by huang3370** [comment]
> > > > 点哪里同步到你哪里去
> > > 
> > > 
> > > pull request 就是拉取请求那里
> > 
> > 
> > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> 
> 对的，获取文件的链接是那个

就是插件。问好提示那个

**Comment by huang3370** [comment]
> > > > > 点哪里同步到你哪里去
> > > > 
> > > > 
> > > > pull request 就是拉取请求那里
> > > 
> > > 
> > > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> > 
> > 
> > 对的，获取文件的链接是那个
> 
> 就是插件。问好提示那个
https://github.com/linyuan0213/MediaRecognitionRule

**Comment by linyuan0213** [comment]
> > > > > > 点哪里同步到你哪里去
> > > > > 
> > > > > 
> > > > > pull request 就是拉取请求那里
> > > > 
> > > > 
> > > > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> > > 
> > > 
> > > 对的，获取文件的链接是那个
> > 
> > 
> > 就是插件。问好提示那个
> > https://github.com/linyuan0213/MediaRecognitionRule

已经改了

**Comment by huang3370** [comment]
> > > > > > 点哪里同步到你哪里去
> > > > > 
> > > > > 
> > > > > pull request 就是拉取请求那里
> > > > 
> > > > 
> > > > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> > > 
> > > 
> > > 对的，获取文件的链接是那个
> > 
> > 
> > 就是插件。问好提示那个
> > https://github.com/linyuan0213/MediaRecognitionRule

![IMG_0101](https://github.com/linyuan0213/nas-tools/assets/165783634/6eb33e63-f2b7-4ee6-b7d0-8c55fafc9709)

**Comment by huang3370** [comment]
> > > > > > > 点哪里同步到你哪里去
> > > > > > 
> > > > > > 
> > > > > > pull request 就是拉取请求那里
> > > > > 
> > > > > 
> > > > > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> > > > 
> > > > 
> > > > 对的，获取文件的链接是那个
> > > 
> > > 
> > > 就是插件。问好提示那个
> > > https://github.com/linyuan0213/MediaRecognitionRule
> 
> 已经改了

是那个？

**Comment by linyuan0213** [comment]
> > > > > > > > 点哪里同步到你哪里去
> > > > > > > 
> > > > > > > 
> > > > > > > pull request 就是拉取请求那里
> > > > > > 
> > > > > > 
> > > > > > ![IMG_0100](https://private-user-images.githubusercontent.com/165783634/320497849-faea3364-d3d2-4c6a-a4c5-6eb61a722ad4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMxNjQsIm5iZiI6MTcxMjU4Mjg2NCwicGF0aCI6Ii8xNjU3ODM2MzQvMzIwNDk3ODQ5LWZhZWEzMzY0LWQzZDItNGM2YS1hNGM1LTZlYjYxYTcyMmFkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTMyNzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM1MzU1MjJjNjIzN2Y2MjZmYzVjMzEwODIxYjg1MThiOTU5OWU2MjA3YWUwMGJhNTM0NDA3OGE3NjE2MWNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtiCDeK2lV6wxsYGr4IWb_1BoNbBWShOrKGE3pq8yRk)这个插件插件，正确么
> > > > > 
> > > > > 
> > > > > 对的，获取文件的链接是那个
> > > > 
> > > > 
> > > > 就是插件。问好提示那个
> > > > https://github.com/linyuan0213/MediaRecognitionRule
> > 
> > 
> > 已经改了
> 
> 是那个？
https://github.com/linyuan0213/MediaRecognitionRule
