### ISSUE TITLE
未搜索到任何资源

### ISSUE THREAD

**Issue by tian4546** [linyuan0213/nas-tools#25]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.2.3 1384b30]
>
> 环境: docker   在群里   Synology里面
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 未搜索到任何资源

沙丘2 未搜索到任何资源

我添加了馒头后 和hdtiem 然后在这2个网站都看到有这个资源
在资源搜索 点击详情 然后点资源搜索按钮 提示 未搜索到任何资源

**Comment by linyuan0213** [comment]
站点维护添加了没

**Comment by huang3370** [comment]
这两个都没问题。估计你自己设置问题

**Comment by tian4546** [comment]
嗯，确实是可以用的，目前 就是和 jackett 不通 一直测试失败

**Comment by linyuan0213** [comment]
> 嗯，确实是可以用的，目前 就是和 jackett 不通 一直测试失败

jackett测试失败看下ip是不是不在同一个ip段里，进docker里ping一下jackett ip，能ping通试试curl看下能不能拿到数据

**Comment by huang3370** [comment]
> 嗯，确实是可以用的，目前 就是和 jackett 不通 一直测试失败
大多人用不了这个无所谓，pt站了还需要这个干嘛
