### ISSUE TITLE
NASTOOL进入站在资源无法下载， 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by w130800** [linyuan0213/nas-tools#29]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: linyuan0213/nas-tools:latest
>
> 环境: docker 
>

## 你遇到什么问题了？

>NASTOOL进入站点资源无法下载 ，报错：Jade.Sinister Beings 2.Ep06.HDTV.1080p.H264-CNHK 添加下载失败 'bool' object has no attribute 'get'
![nas](https://github.com/linyuan0213/nas-tools/assets/166583314/ad14e06c-b0d1-4d46-81cc-958644f11edd)

订阅也显示报错
![nas4](https://github.com/linyuan0213/nas-tools/assets/166583314/da4533a4-4a8e-480a-9906-39d2716cee16)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 帮忙指出问题。

## 给出程序界面截图、后台运行日志或配置文件
![nas5](https://github.com/linyuan0213/nas-tools/assets/166583314/773a8261-f5b4-4472-9d7f-76016b91fd85)

![nas1](https://github.com/linyuan0213/nas-tools/assets/166583314/42a94259-e8c2-4834-aaf9-bd3df0da2278)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![nas3](https://github.com/linyuan0213/nas-tools/assets/166583314/ef4fc331-0357-4e1b-a269-10472d8fdc50)

**Comment by w130800** [comment]
![nas4](https://github.com/linyuan0213/nas-tools/assets/166583314/da4533a4-4a8e-480a-9906-39d2716cee16)

**Comment by linyuan0213** [comment]
> ![nas4](https://private-user-images.githubusercontent.com/166583314/321112193-da4533a4-4a8e-480a-9906-39d2716cee16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzAyMTQsIm5iZiI6MTcxMjcyOTkxNCwicGF0aCI6Ii8xNjY1ODMzMTQvMzIxMTEyMTkzLWRhNDUzM2E0LTRhOGUtNDgwYS05OTA2LTM5ZDI3MTZjZWUxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzhlNWMzYjc2ODk2N2UyNGU5MGRkMzViY2FlMTRlNzc0NzhhYjlhNzg2NmRmNTMxYWVjZGY1NjNhM2U4ODFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xbJBwYf-qq3Bz9G5Hv6MisjUY4cOqSIc5LODpdqLtEQ)

nyaa的资源是吧？

**Comment by linyuan0213** [comment]
> m-team的资源

馒头我测了不存在这种问题啊，你把镜像重新拉一下

**Comment by w130800** [comment]
好的，我把dock坏境再搞一下，再试试

**Comment by linyuan0213** [comment]
> 好的，我把dock坏境再搞一下，再试试

解决了吗？没问题我就关了这个issue 了

**Comment by w130800** [comment]
好的，没问题了，重新拉了数据，能下载，也能订阅了， 目前就是站点测试不通，会提示COOKIE失效，不过也不影响使用。没所谓，

**Comment by linyuan0213** [comment]
> 好的，没问题了，重新拉了数据，能下载，也能订阅了， 目前就是站点测试不通，会提示COOKIE失效，不过也不影响使用。没所谓，

这个不要填 cookie，填请求头参数就行，cookie 空着，把仿真关了
