### ISSUE TITLE
更新后无法在页面提交下载任务

### ISSUE THREAD

**Issue by decretumer** [linyuan0213/nas-tools#3]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
>v3.2.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 在站点资源与资源搜索页面直接点击下载按钮，无法弹出下载配置界面，官方的镜像应该不存在这个问题，推测是bug

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![EEF3D823-45DA-4B0A-9D9F-4B219BCFEFFB](https://user-images.githubusercontent.com/132173585/235328738-fc240b75-70fe-4e4f-8b24-c54a9494717f.png)
此处点击下载按钮，正常应该弹出一个窗体，然后进行下载器选择和下载路径的配置。但是现在是没有反应
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by linyuan0213** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本:
> > v3.2.1
> > 环境: docker or windows or Synology
> > docker
> 
> ## 你遇到什么问题了？
> > 在站点资源与资源搜索页面直接点击下载按钮，无法弹出下载配置界面，官方的镜像应该不存在这个问题，推测是bug
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> 
> ## 你期望的结果
> > 描述以下你期望的结果
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> ![EEF3D823-45DA-4B0A-9D9F-4B219BCFEFFB](https://user-images.githubusercontent.com/132173585/235328738-fc240b75-70fe-4e4f-8b24-c54a9494717f.png) 此处点击下载按钮，正常应该弹出一个窗体，然后进行下载器选择和下载路径的配置。但是现在是没有反应
> 
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供docker的日志

我这里没问题，F12检查下是不是网络问题
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/26356991/236367635-0c661df7-b23e-4880-979c-471a8c5d2817.png">

**Comment by linyuan0213** [comment]
> get_download_dirs

不确定是什么问题引起的，我这边没法复现，麻烦F12点下下载给我看下这个
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26356991/236593181-4867e98b-4560-4be6-90ac-26533e47ceeb.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/26356991/236593194-ddab439e-968b-453a-b929-ad6017630f89.png">

**Comment by linyuan0213** [comment]
还有这里是不是选了默认？
<img width="287" alt="image" src="https://user-images.githubusercontent.com/26356991/236593534-c1d636da-83d3-4fba-84e0-7ff9ebf2a9ac.png">

**Comment by linyuan0213** [comment]
> > 还有这里是不是选了默认？ <img alt="image" width="287" src="https://user-images.githubusercontent.com/26356991/236593534-c1d636da-83d3-4fba-84e0-7ff9ebf2a9ac.png">
> 
> 并没有设置默认
> 
> 这是F12之后的报错 ![image](https://user-images.githubusercontent.com/96988242/236614590-e568f7a2-4351-48eb-a9db-98ac6d1dff39.png)

需要设置下默认下载器，把这个星点上

**Comment by linyuan0213** [comment]
> > > > 还有这里是不是选了默认？ <img alt="image" width="287" src="https://user-images.githubusercontent.com/26356991/236593534-c1d636da-83d3-4fba-84e0-7ff9ebf2a9ac.png">
> > > 
> > > 
> > > 并没有设置默认
> > > 这是F12之后的报错 ![image](https://user-images.githubusercontent.com/96988242/236614590-e568f7a2-4351-48eb-a9db-98ac6d1dff39.png)
> > 
> > 
> > 需要设置下默认下载器，把这个星点上
> 
> 已经设置为默认下载器了
> 
> 但是还是无法跳出下载提示,F12查看后提示如下 ![image](https://user-images.githubusercontent.com/96988242/236617890-cc0da165-bad2-479a-a84c-3866ff2b54b6.png)

F12点下第一个do，两个链接都看下，如果不对看下下载器的预设

**Comment by linyuan0213** [comment]
> 第一个do ![image](https://user-images.githubusercontent.com/96988242/236619127-181c2a67-dd06-449e-b8b7-e509a211d275.png)
> 
> 第二个do ![image](https://user-images.githubusercontent.com/96988242/236619140-af2225c6-ac5d-4230-88cc-d9596bf40131.png)
> 
> 下载器设置如下 ![image](https://user-images.githubusercontent.com/96988242/236619156-213a66c1-c1d0-4176-b8a3-83e0217c996a.png)
> 
> ![image](https://user-images.githubusercontent.com/96988242/236619204-4086df38-3298-407c-9df9-d0486e3d0992.png)

现在应该是正常了，弹不出来刷新下或者清下缓存

**Comment by linyuan0213** [comment]
> 无痕 缓存 包括重启容器都试过了 但是还是无法弹出下载，试了一下手动添加种子还是没反应
> ![image](https://user-images.githubusercontent.com/96988242/236619835-d9b0797a-302b-4af2-ba81-597efbdd90c9.png)

F12 看下有报错没有

**Comment by linyuan0213** [comment]
> > > 无痕 缓存 包括重启容器都试过了 但是还是无法弹出下载，试了一下手动添加种子还是没反应
> > > ![image](https://user-images.githubusercontent.com/96988242/236619835-d9b0797a-302b-4af2-ba81-597efbdd90c9.png)
> > 
> > 
> > F12 看下有报错没有
> 
> 并没有

🤔那不应该啊，我加你qq吧

**Comment by linyuan0213** [comment]
> > > > 无痕 缓存 包括重启容器都试过了 但是还是无法弹出下载，试了一下手动添加种子还是没反应
> > > > ![image](https://user-images.githubusercontent.com/96988242/236619835-d9b0797a-302b-4af2-ba81-597efbdd90c9.png)
> > > 
> > > 
> > > F12 看下有报错没有
> > 
> > 
> > 并没有
> 
> 🤔那不应该啊，我加你qq吧

或者换个浏览器试试

**Comment by linyuan0213** [comment]
> > > > > > 无痕 缓存 包括重启容器都试过了 但是还是无法弹出下载，试了一下手动添加种子还是没反应
> > > > > > ![image](https://user-images.githubusercontent.com/96988242/236619835-d9b0797a-302b-4af2-ba81-597efbdd90c9.png)
> > > > > 
> > > > > 
> > > > > F12 看下有报错没有
> > > > 
> > > > 
> > > > 并没有
> > > 
> > > 
> > > 🤔那不应该啊，我加你qq吧
> > 
> > 
> > 或者换个浏览器试试
> 
> 很抱歉现在才看到你的回复,尝试换了三个浏览器还是不行 😔

那我加下你qq，给我录个视频？

**Comment by linyuan0213** [comment]
> > > > > > > > 无痕 缓存 包括重启容器都试过了 但是还是无法弹出下载，试了一下手动添加种子还是没反应
> > > > > > > > ![image](https://user-images.githubusercontent.com/96988242/236619835-d9b0797a-302b-4af2-ba81-597efbdd90c9.png)
> > > > > > > 
> > > > > > > 
> > > > > > > F12 看下有报错没有
> > > > > > 
> > > > > > 
> > > > > > 并没有
> > > > > 
> > > > > 
> > > > > 🤔那不应该啊，我加你qq吧
> > > > 
> > > > 
> > > > 或者换个浏览器试试
> > > 
> > > 
> > > 很抱歉现在才看到你的回复,尝试换了三个浏览器还是不行 😔
> > 
> > 
> > 那我加下你qq，给我录个视频？
> 
> 可以,那我qq账号就通过邮件的方式发你了

linyuan213@gmail.com
