### ISSUE TITLE
今天崩了，怎么搞都解决不了，日期不会看，帮帮忙

### ISSUE THREAD

**Issue by lord312** [linyuan0213/nas-tools#31]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新
>
> 环境: docker 
![28b6dc161d2d328cbd39b8260cf194d](https://github.com/linyuan0213/nas-tools/assets/128642187/4bce3f0f-9278-473f-8a35-6d9ca53f9f0c)

**Comment by linyuan0213** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: 最新
> > 环境: docker
> > ![28b6dc161d2d328cbd39b8260cf194d](https://private-user-images.githubusercontent.com/128642187/326229081-4bce3f0f-9278-473f-8a35-6d9ca53f9f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDc0ODUsIm5iZiI6MTcxNDMwNzE4NSwicGF0aCI6Ii8xMjg2NDIxODcvMzI2MjI5MDgxLTRiY2UzZjBmLTkyNzgtNDczZi04YTM1LTZkOWNhNTNmOWYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxMjI2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZThiM2UxMDZmYTFkMzkwZmVjYTQxNzA0N2VmZDdiMTcxOGQyYzNjMjJkZDliMTc0ZDgwY2M5ZDJmMTJiMTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jf-Qu-9wajAvEq-ayyMnJmXc918wkR3TJY1T85z7jWE)

拉下最新的镜像，这个版本我在readme 上说明了需要最新镜像
