### ISSUE TITLE
订阅突然不自动更新了，日志显示有报错

### ISSUE THREAD

**Issue by zzQ894416361** [linyuan0213/nas-tools#37]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.3.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

、订阅突然就不自动更新了，日志里报如图所示的错误

![image](https://github.com/linyuan0213/nas-tools/assets/112358410/6fa8ad86-13e4-45dd-9c29-bb5695218d81)

**Comment by linyuan0213** [comment]
索引器选了哪几个站？

**Comment by zzQ894416361** [comment]
![Uploading 76a817e11c0482d65f73308f0576e2c.png…]()

**Comment by zzQ894416361** [comment]
![76a817e11c0482d65f73308f0576e2c](https://github.com/linyuan0213/nas-tools/assets/112358410/d2beb17f-9889-4ed9-830b-c773150da51d)
![b8dc2e9339214f21767aeeb91f91be4](https://github.com/linyuan0213/nas-tools/assets/112358410/27b7c55b-cb98-4997-8c4b-39235655a7de)
![ee13aa57c68fa2bff2056532053c9ba](https://github.com/linyuan0213/nas-tools/assets/112358410/eeabe304-2811-4057-b428-a19aaa25e4ee)
只选了馒头

**Comment by linyuan0213** [comment]
> ![76a817e11c0482d65f73308f0576e2c](https://private-user-images.githubusercontent.com/112358410/331013499-d2beb17f-9889-4ed9-830b-c773150da51d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4NTEsIm5iZiI6MTcxNTgyMzU1MSwicGF0aCI6Ii8xMTIzNTg0MTAvMzMxMDEzNDk5LWQyYmViMTdmLTk4ODktNGVkOS04MzBiLWM3NzMxNTBkYTUxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwMTM5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWZkZjY0YTE4NmZhOWI3NzdhZTNhYmUwZDhlMDNiNjI4MDU0ZWVmNjVkNmIzNTU5MjA2YWZmZjcyZTgwNWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B1E_Xo_lGKibtK88rLJbH5tqcPCB0-1W19TOMg8Hon4) ![b8dc2e9339214f21767aeeb91f91be4](https://private-user-images.githubusercontent.com/112358410/331013509-27b7c55b-cb98-4997-8c4b-39235655a7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4NTEsIm5iZiI6MTcxNTgyMzU1MSwicGF0aCI6Ii8xMTIzNTg0MTAvMzMxMDEzNTA5LTI3YjdjNTViLWNiOTgtNDk5Ny04YzRiLTM5MjM1NjU1YTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwMTM5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTNiM2UxM2Q4MjIyYTExZDAwYjA0ZjBhNGUzODdkYjc3MjMwZDliZjY1MzFiZWI3NDYwMzNkMGUzNDYyNGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C5KScIOsdXZsC3Jr6xrpCni_R7z2PXfAQqKYu5KheZg) ![ee13aa57c68fa2bff2056532053c9ba](https://private-user-images.githubusercontent.com/112358410/331013518-eeabe304-2811-4057-b428-a19aaa25e4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjM4NTEsIm5iZiI6MTcxNTgyMzU1MSwicGF0aCI6Ii8xMTIzNTg0MTAvMzMxMDEzNTE4LWVlYWJlMzA0LTI4MTEtNDA1Ny1iNDI4LWExOWFhYTI1ZTRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwMTM5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjdlYWE2MjBmZmNlNWJhN2EwMTgzZjc4ZDI2NDdjZDcwMDIxN2E0YWU4Nzk5YzAzNTRiMGUyN2Q0OWFhZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ABQOaCULscSBRQWwsbmCtgrw-K7oUu5rgT0a1ZwpzWc) 只选了馒头

站点配置也发一下，注意打码

**Comment by linyuan0213** [comment]
测了下，我这里不存在这种问题，如果配置没问题，删掉容器和数据重新安装试试
<img width="1096" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/26356991/a0a4ab67-ecf4-4ad3-9b2e-06e62b01149f">

**Comment by zzQ894416361** [comment]
好的谢谢大佬、我重新订阅了下 好像是可以下载了

**Comment by zzQ894416361** [comment]
感谢回复
