### ISSUE TITLE
Jackett 测试成功，但是搜索资源时全部失败

### ISSUE THREAD

**Issue by Edger** [linyuan0213/nas-tools#4]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> NASTools 可以添加 Jackett 并测试成功，但是在电影详情页里面点击搜索资源会失败，查看下载器统计数据发现所有请求都失败了。
但是在 Jackett 那里手动搜索是可以搜到资源的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 可以正常搜索到资源

## 给出程序界面截图、后台运行日志或配置文件

> 
<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/0372590d-4bc2-4663-9e56-140c45e06299">

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/4079015d-c2ec-4b6b-ac2b-eeaaafffca7b">

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/079a1cd6-1be2-4e2f-869c-caebd22a494d">

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/b4b1edeb-1542-4498-935c-1464928b6855">

**Comment by linyuan0213** [comment]
把搜到的名字放到名称识别测试里看下能不能识别到

**Comment by Edger** [comment]
> 把搜到的名字放到名称识别测试里看下能不能识别到，速度激情 5 看里面好像没有

@linyuan0213 

没有，搜了很多电影都没有，而且看这个日志的耗时也不对吧，都是 0 毫秒

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/9a06e4af-0249-4c87-a7a7-aa5e9767f846">

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/e85c0f8f-07a3-460c-9aad-a68e58e33427">

<img width="720" alt="Snipaste_2023-05-21_23-15-09" src="https://github.com/linyuan0213/nas-tools/assets/18591042/a1b2c89b-f807-438c-90e1-bf41745b5824">

<img width="720" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/18591042/a68d3d87-3b44-4639-8a07-824011b161a0">

**Comment by linyuan0213** [comment]
> > 把搜到的名字放到名称识别测试里看下能不能识别到，速度激情 5 看里面好像没有
> 
> @linyuan0213
> 
> 没有，搜了很多电影都没有，而且看这个日志的耗时也不对吧，都是 0 毫秒
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751088-9a06e4af-0249-4c87-a7a7-aa5e9767f846.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751143-e85c0f8f-07a3-460c-9aad-a68e58e33427.png"> <img alt="Snipaste_2023-05-21_23-15-09" width="720" src="https://user-images.githubusercontent.com/18591042/239751181-a1b2c89b-f807-438c-90e1-bf41745b5824.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239750717-a68d3d87-3b44-4639-8a07-824011b161a0.png">

能识别就检查一下你的规则过滤是不是给过滤了

**Comment by Edger** [comment]
> > > 把搜到的名字放到名称识别测试里看下能不能识别到，速度激情 5 看里面好像没有
> > 
> > 
> > @linyuan0213
> > 没有，搜了很多电影都没有，而且看这个日志的耗时也不对吧，都是 0 毫秒
> > <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751088-9a06e4af-0249-4c87-a7a7-aa5e9767f846.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751143-e85c0f8f-07a3-460c-9aad-a68e58e33427.png"> <img alt="Snipaste_2023-05-21_23-15-09" width="720" src="https://user-images.githubusercontent.com/18591042/239751181-a1b2c89b-f807-438c-90e1-bf41745b5824.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239750717-a68d3d87-3b44-4639-8a07-824011b161a0.png">
> 
> 能识别就检查一下你的规则过滤是不是给过滤了

上面有截图可以看到名称识别是正常的，而且我把规则过滤关了还是一样的情况

感觉是 NASTool 没有等待到 Jackett 的结果返回，就判断失败了

**Comment by linyuan0213** [comment]
> > > > 把搜到的名字放到名称识别测试里看下能不能识别到，速度激情 5 看里面好像没有
> > > 
> > > 
> > > @linyuan0213
> > > 没有，搜了很多电影都没有，而且看这个日志的耗时也不对吧，都是 0 毫秒
> > > <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751088-9a06e4af-0249-4c87-a7a7-aa5e9767f846.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751143-e85c0f8f-07a3-460c-9aad-a68e58e33427.png"> <img alt="Snipaste_2023-05-21_23-15-09" width="720" src="https://user-images.githubusercontent.com/18591042/239751181-a1b2c89b-f807-438c-90e1-bf41745b5824.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239750717-a68d3d87-3b44-4639-8a07-824011b161a0.png">
> > 
> > 
> > 能识别就检查一下你的规则过滤是不是给过滤了
> 
> 上面有截图可以看到名称识别是正常的，而且我把规则过滤关了还是一样的情况
> 
> 感觉是 NASTool 没有等待到 Jackett 的结果返回，就判断失败了

我先看下，这两天有点忙

**Comment by Edger** [comment]
> > > > > 把搜到的名字放到名称识别测试里看下能不能识别到，速度激情 5 看里面好像没有
> > > > 
> > > > 
> > > > @linyuan0213
> > > > 没有，搜了很多电影都没有，而且看这个日志的耗时也不对吧，都是 0 毫秒
> > > > <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751088-9a06e4af-0249-4c87-a7a7-aa5e9767f846.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239751143-e85c0f8f-07a3-460c-9aad-a68e58e33427.png"> <img alt="Snipaste_2023-05-21_23-15-09" width="720" src="https://user-images.githubusercontent.com/18591042/239751181-a1b2c89b-f807-438c-90e1-bf41745b5824.png"> <img alt="image" width="720" src="https://user-images.githubusercontent.com/18591042/239750717-a68d3d87-3b44-4639-8a07-824011b161a0.png">
> > > 
> > > 
> > > 能识别就检查一下你的规则过滤是不是给过滤了
> > 
> > 
> > 上面有截图可以看到名称识别是正常的，而且我把规则过滤关了还是一样的情况
> > 感觉是 NASTool 没有等待到 Jackett 的结果返回，就判断失败了
> 
> 我先看下，这两天有点忙

好的，辛苦大佬了

**Comment by linyuan0213** [comment]
> 3.2.2 版本中无法添加 jackett，具体表现为正确输入 jackett 的地址和 API 后，测试失败。作为对比，用原版 nastool 能正常添加和使用。

提供下截图和日志信息

**Comment by linyuan0213** [comment]
@Edger 我这里使用 BullTorrent 搜索是正常的，请检查一下是不是你的网络或者其他的连接出问题了
<img width="1440" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/26356991/9daee8ee-b09a-43b4-9978-30084f33adba">

**Comment by Heisenberglue** [comment]
> 3.2.2 版本中无法添加 jackett，具体表现为正确输入 jackett 的地址和 API 后，测试失败。作为对比，用原版 nastool 能正常添加和使用。

网络都是正常的，nastool、jackett 都能正常访问互联网。图片如下，log等级开到 ERROR 也没看到啥有用信息。另外观察到 prowlarr 也是一样的问题，添加后不能识别出来，点测试后过一会报“失败”。
![1.png](https://img1.imgtp.com/2023/06/10/DOzaa3Yr.png)
![2.png](https://img1.imgtp.com/2023/06/10/FlemW96g.png)
![3.png](https://img1.imgtp.com/2023/06/10/IfV671rc.png)
![4.png](https://img1.imgtp.com/2023/06/10/EGCbjo9W.png)
![5.png](https://img1.imgtp.com/2023/06/10/wnfjCIun.png)

**Comment by linyuan0213** [comment]
> > 3.2.2 版本中无法添加 jackett，具体表现为正确输入 jackett 的地址和 API 后，测试失败。作为对比，用原版 nastool 能正常添加和使用。
> 
> 网络都是正常的，nastool、jackett 都能正常访问互联网。图片如下，log等级开到 ERROR 也没看到啥有用信息。另外观察到 prowlarr 也是一样的问题，添加后不能识别出来，点测试后过一会报“失败”。 ![1.png](https://camo.githubusercontent.com/89d5c241040c0e78a7d9a4538a57f48621de9eb290f7cc34f431ef1387809e9d/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f444f7a61613359722e706e67) ![2.png](https://camo.githubusercontent.com/655767f5d06cca85007246147fde0a924d49d8c6af151f3d45c42d7c46d06b09/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f466c656d573936672e706e67) ![3.png](https://camo.githubusercontent.com/64e49481f7a41989d7de6e81c2668f2976f9a0f92aa4c27bfd122b13352786b1/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f49665636373172632e706e67) ![4.png](https://camo.githubusercontent.com/18811c7c4053a73d0032917864656158e53a9d68be9aad97f0eaa5e0783ff31b/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f454743626a6f39572e706e67) ![5.png](https://camo.githubusercontent.com/4b4bb64bb1d52f55417fcf4121c9f1af2747996c62841d87a6b1f5de8f96ef45/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f776e666a4349756e2e706e67)

jackett有设置密码吗？docker部署的话进入docker里面ping一下jackett的ip看是不是能ping通

**Comment by Heisenberglue** [comment]
可以 ping 通，我所有的 docker 都是部署在同一台设备上的。
jackett 也没有设置密码。😔

**Comment by linyuan0213** [comment]
> 可以 ping 通，我所有的 docker 都是部署在同一台设备上的。 jackett 也没有设置密码。😔

可以远程吗？可以的话给你看下

**Comment by Heisenberglue** [comment]
可以远程的话就太感谢啦，已通过邮件联系
