### ISSUE TITLE
订阅添加下载任务失败

### ISSUE THREAD

**Issue by guobaizhu** [linyuan0213/nas-tools#40]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.4.8
>
> 环境: docker
>

## 你遇到什么问题了？

> 订阅添加下载任务失败，提示让查下载器。但是刷流和站点资源一键下载都是正常的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无法解决

## 给出程序界面截图、后台运行日志或配置文件
![屏幕截图 2024-06-11 165045](https://github.com/linyuan0213/nas-tools/assets/166461561/b63bb0fe-3244-459c-a74c-455ef4c2b273)

**Comment by linyuan0213** [comment]
我看下

**Comment by linyuan0213** [comment]
<img width="951" alt="image" src="https://github.com/linyuan0213/nas-tools/assets/26356991/b9222f83-d1b0-49a2-90e9-5aef985032b4">
调试了一下，我这里是正常的，你再重新刷新下试试，可能是因为当时馒头的接口不稳定导致的

**Comment by guobaizhu** [comment]
确实好了……
感觉馒头最近是不太对劲，之前刷流任务也是疯狂报访问太频繁

**Comment by linyuan0213** [comment]
> 确实好了…… 感觉馒头最近是不太对劲，之前刷流任务也是疯狂报访问太频繁

是的，馒头最近都在更新，可能有点不稳定，把刷流的时间间隔调大点
