### ISSUE TITLE
可以加入迅雷下载吗

### ISSUE THREAD

**Issue by cybaijie** [linyuan0213/nas-tools#5]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 能加入迅雷下载吗

## 这个功能有什么可以参考的资料吗？

> [这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.](https://pan.xunlei.com/yc/upload/)这个是迅雷下载的链接

**Comment by linyuan0213** [comment]
暂不考虑迅雷
