### ISSUE TITLE
新增企业微信可信IP更新插件

### ISSUE THREAD

**Issue by k2y1982** [linyuan0213/nas-tools#55]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.5.6
>
> 环境: docker
>

## 你遇到什么问题了？

> 没有更新信任IP，希望有具体一点的说明

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://github.com/user-attachments/assets/60e2cd0b-3a2c-4613-a6e8-2fde35578859)

**Comment by linyuan0213** [comment]
下个版本优化下日志

**Comment by k2y1982** [comment]
插件是可用的，我刚刚测试成功了，只是实时日志报错的状态没有输出而已，报错的日志需在docker后台日志里看。
我选的是不覆盖之前的IP
1.信任IP里没有任何IP时会报错。
2.信任IP里有相同IP时会报错。
3.删除当前IP，保留几个曾经的信任IP后，修改成功。

**Comment by k2y1982** [comment]
终于把表达式学会了。5位其实就是去掉了第1位的秒和第7位的年，
分钟-小时-一个月中的第几天（1~31）-月份（1~12）-星期几（0-6 周日为0）
0 1-6/5 * * * 就是 每天的1点至6点间，间隔5小时运行一次，也就是1点运行一次，6点运行一次，别的时间不运行。
https://tooltt.com/crontab/

**Comment by linyuan0213** [comment]
> 插件是可用的，我刚刚测试成功了，只是实时日志报错的状态没有输出而已，报错的日志需在docker后台日志里看。 我选的是不覆盖之前的IP 1.信任IP里没有任何IP时会报错。 2.信任IP里有相同IP时会报错。 3.删除当前IP，保留几个曾经的信任IP后，修改成功。

获取微信信任 ip 为空会报错，目前需要保证里面有一个 ip，下个版本会修复

**Comment by linyuan0213** [comment]
> `终于把表达式学会了。5位其实就是去掉了第1位的秒和第7位的年，` `分钟-小时-一个月中的第几天（1~31）-月份（1~12）-星期几（0~6 周日为0）` `0 1-6/5 * * * 就是 每天的1点至6点间，间隔5小时运行一次，也就是1点运行一次，6点运行一次，别的时间不运行。` https://tooltt.com/crontab/

是的，搜五位 cron 表达式就行，这里还可以直接写成 0 1,6 * * *，1 点和 6 点运行一次
