### ISSUE TITLE
请问为啥不提供windows版本

### ISSUE THREAD

**Issue by zc16607** [linyuan0213/nas-tools#58]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: fork最新的master分支
>
> 环境: windows

## 你想要新增或者改进什么功能？
我自己fork了一份你的代码，加了一个打包windows版本的工作流，补全了一些模块(requirement_old.txt)
运行后确实能打包成功windows版本，下载地址https://github.com/zc16607/nas-tools-temp2/actions/runs/11029963856

运行之后报错提示连接不上redis，然后我又下载了一个redis for windows，重新运行nas-tools，这个时候网页提示sqlLite3数据库的表缺少什么字段。实在绷不住了，有没有简单的办法可以用上你的最新代码 for windows版本

**Comment by zc16607** [comment]
报错如下：
```
OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TORRENT_REMOVE_TASK.ONLYNASTOOL [SQL: SELECT "TORRENT_REMOVE_TASK"."ID" AS "TORRENT_REMOVE_TASK_ID", "TORRENT_REMOVE_TASK"."NAME" AS "TORRENT_REMOVE_TASK_NAME", "TORRENT_REMOVE_TASK"."ACTION" AS "TORRENT_REMOVE_TASK_ACTION", "TORRENT_REMOVE_TASK"."INTERVAL" AS "TORRENT_REMOVE_TASK_INTERVAL", "TORRENT_REMOVE_TASK"."ENABLED" AS "TORRENT_REMOVE_TASK_ENABLED", "TORRENT_REMOVE_TASK"."SAMEDATA" AS "TORRENT_REMOVE_TASK_SAMEDATA", "TORRENT_REMOVE_TASK"."ONLYNASTOOL" AS "TORRENT_REMOVE_TASK_ONLYNASTOOL", "TORRENT_REMOVE_TASK"."DOWNLOADER" AS "TORRENT_REMOVE_TASK_DOWNLOADER", "TORRENT_REMOVE_TASK"."CONFIG" AS "TORRENT_REMOVE_TASK_CONFIG", "TORRENT_REMOVE_TASK"."NOTE" AS "TORRENT_REMOVE_TASK_NOTE" FROM "TORRENT_REMOVE_TASK" ORDER BY "TORRENT_REMOVE_TASK"."NAME"] (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by linyuan0213** [comment]
> 报错如下：
> 
> ```
> OperationalError
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TORRENT_REMOVE_TASK.ONLYNASTOOL [SQL: SELECT "TORRENT_REMOVE_TASK"."ID" AS "TORRENT_REMOVE_TASK_ID", "TORRENT_REMOVE_TASK"."NAME" AS "TORRENT_REMOVE_TASK_NAME", "TORRENT_REMOVE_TASK"."ACTION" AS "TORRENT_REMOVE_TASK_ACTION", "TORRENT_REMOVE_TASK"."INTERVAL" AS "TORRENT_REMOVE_TASK_INTERVAL", "TORRENT_REMOVE_TASK"."ENABLED" AS "TORRENT_REMOVE_TASK_ENABLED", "TORRENT_REMOVE_TASK"."SAMEDATA" AS "TORRENT_REMOVE_TASK_SAMEDATA", "TORRENT_REMOVE_TASK"."ONLYNASTOOL" AS "TORRENT_REMOVE_TASK_ONLYNASTOOL", "TORRENT_REMOVE_TASK"."DOWNLOADER" AS "TORRENT_REMOVE_TASK_DOWNLOADER", "TORRENT_REMOVE_TASK"."CONFIG" AS "TORRENT_REMOVE_TASK_CONFIG", "TORRENT_REMOVE_TASK"."NOTE" AS "TORRENT_REMOVE_TASK_NOTE" FROM "TORRENT_REMOVE_TASK" ORDER BY "TORRENT_REMOVE_TASK"."NAME"] (Background on this error at: https://sqlalche.me/e/20/e3q8)
> ```

把 user.db 删掉重新运行就行

**Comment by zc16607** [comment]
> > 报错如下：
> > ```
> > OperationalError
> > sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TORRENT_REMOVE_TASK.ONLYNASTOOL [SQL: SELECT "TORRENT_REMOVE_TASK"."ID" AS "TORRENT_REMOVE_TASK_ID", "TORRENT_REMOVE_TASK"."NAME" AS "TORRENT_REMOVE_TASK_NAME", "TORRENT_REMOVE_TASK"."ACTION" AS "TORRENT_REMOVE_TASK_ACTION", "TORRENT_REMOVE_TASK"."INTERVAL" AS "TORRENT_REMOVE_TASK_INTERVAL", "TORRENT_REMOVE_TASK"."ENABLED" AS "TORRENT_REMOVE_TASK_ENABLED", "TORRENT_REMOVE_TASK"."SAMEDATA" AS "TORRENT_REMOVE_TASK_SAMEDATA", "TORRENT_REMOVE_TASK"."ONLYNASTOOL" AS "TORRENT_REMOVE_TASK_ONLYNASTOOL", "TORRENT_REMOVE_TASK"."DOWNLOADER" AS "TORRENT_REMOVE_TASK_DOWNLOADER", "TORRENT_REMOVE_TASK"."CONFIG" AS "TORRENT_REMOVE_TASK_CONFIG", "TORRENT_REMOVE_TASK"."NOTE" AS "TORRENT_REMOVE_TASK_NOTE" FROM "TORRENT_REMOVE_TASK" ORDER BY "TORRENT_REMOVE_TASK"."NAME"] (Background on this error at: https://sqlalche.me/e/20/e3q8)
> > ```
> 
> 把 user.db 删掉重新运行就行

可以了，感谢！
