### ISSUE TITLE
群晖 docker 警告打不开

### ISSUE THREAD

**Issue by ziyefeixing** [linyuan0213/nas-tools#60]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.5.6
>
> 环境: Synology
>

## 你遇到什么问题了？

nastool运行一段时间之后会出现警告提示，然后就进不去了，重启之后短暂可以进入 之后又进不去了。

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

已经浏览过 没有看到这样的问题

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

![photo_2024-10-16_02-02-31](https://github.com/user-attachments/assets/d6e9d013-047f-4130-9c67-f289bd43290f)
![photo_2024-10-16_02-02-25](https://github.com/user-attachments/assets/c557833b-91da-452b-858d-21746c26b6ce)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by linyuan0213** [comment]
yaml出问题了，如果有备份config.yaml导入备份的，没有就重新配置下

**Comment by ziyefeixing** [comment]
> yaml出问题了，如果有备份config.yaml导入备份的，没有就重新配置下

OK  我尝试一下 感谢大佬~
