### ISSUE TITLE
Docker 容器报警 [WARNING] Invalid request from ip=::ffff:127.0.0.1: [SSL: HTTP_REQUEST] http request (_ssl.c:2580)

### ISSUE THREAD

**Issue by Minlison** [linyuan0213/nas-tools#63]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.6.1
>
> 环境: docker or windows or Synology
> Synology Docker Container

## 你遇到什么问题了？
启动后容器报警 [WARNING] Invalid request from ip=::ffff:127.0.0.1: [SSL: HTTP_REQUEST] http request (_ssl.c:2580)
<img width="1621" alt="image" src="https://github.com/user-attachments/assets/2d7eb5fe-a745-4d8a-b210-caf0543533c0">

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果

去除这个警告

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by linyuan0213** [comment]
给下设置
