### ISSUE TITLE
【自动删种】功能，设置状态之后无法筛选出符合条件的种子

### ISSUE THREAD

**Issue by ziyefeixing** [linyuan0213/nas-tools#64]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.6.1
> 环境: docker
>qb版本：4.6.7 docker

## 你遇到什么问题了？

【NASTOOLS】中有一个【自动删种】的功能。其他条件都能匹配上，但是【种子状态】这个设置之后，无法正常筛选出符合条件的种子。我设置的种子状态是【error】/【stalledDL】这两个，都无法正常匹配上，希望大佬检查修复一下。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是的

## 你期望的结果

希望大佬修复一下【自动删种】只设置【种子状态】的时候无法匹配到符合条件的种子的问题。

## 给出程序界面截图、后台运行日志或配置文件

![Snipaste_2024-11-29_04-02-12](https://github.com/user-attachments/assets/8af4fde8-91dc-41f4-83a6-ff8cfbf767fb)

**Comment by linyuan0213** [comment]
ok我看看什么情况，有问题下一版修复

**Comment by ziyefeixing** [comment]
> ok我看看什么情况，有问题下一版修复

OK 感谢大佬

**Comment by linyuan0213** [comment]
'Downloading', 'Uploading', 'Checking', 'Queued', 'Paused', 'Stopped', 'Pending', 'Error', 'Unknown'自动删种换成这几种状态，前端页面我抽时间改下，这版忘改了

**Comment by linyuan0213** [comment]
最新3.6.3已经修复
