### ISSUE TITLE
多个索引器同时使用

### ISSUE THREAD

**Issue by ojbgame** [linyuan0213/nas-tools#7]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 同时支持多个索引器，可同时搜索PT站、Jackett的内容

**Comment by linyuan0213** [comment]
jackett配置pt站不就可以了吗，这样会导致内容重复，不打算支持
